import mongoose from "mongoose";
import { Alert } from "../models/Alert";
import { Camera } from "../models/Camera";
import { ApiError } from "../utils/ApiError";
import { JwtAccessPayload } from "../types";
import { validateCameraAccess } from "./camera.service";
import { logActivity } from "../models/ActivityLog";
import { socketService } from "./socket.service";
import { sendPushNotification } from "./notification.service";

/**
 * Create Manual Alert
 * Logs a new manually triggered alert from an operator or customer.
 * Emits a real-time 'new_alert' Socket.IO event and triggers a push notification.
 * 
 * @param data - The alert payload (type, priority, description, etc.)
 * @param user - The authenticated user triggering the alert
 */
export const createAlert = async (data: any, user: JwtAccessPayload) => {
  const camera = await Camera.findOne({ _id: data.cameraId, isDeleted: false });
  if (!camera) throw ApiError.notFound("Camera");
  await validateCameraAccess(camera, user);

  const alert = await Alert.create({
    ...data,
    createdBy: user.userId,
    status: "new",
  });

  // Emit real-time socket event
  socketService.emitToCamera(data.cameraId, "new_alert", alert);

  // Send push notification to customers/operators who own/monitor the camera
  // Assuming camera.customerId or camera.operatorIds exists.
  if (camera.customerId) {
    await sendPushNotification(
      camera.customerId.toString(),
      `New Alert: ${camera.name}`,
      `A new ${data.type} alert was generated by ${user.role}.`
    );
  }

  logActivity({
    userId: new mongoose.Types.ObjectId(user.userId),
    action: "ALERT_CREATED",
    description: `Manually triggered a ${data.type} alert for camera ${camera.name}`,
    metadata: { alertId: alert._id, cameraId: data.cameraId },
  });

  return alert;
};

/**
 * List Alerts (Paginated & Filtered)
 * Retrieves a list of alerts based on query filters.
 * Automatically restricts access so non-admins only see alerts for cameras they are assigned to.
 * 
 * @param query - Filtering and pagination parameters
 * @param user - The requesting user
 */
export const listAlerts = async (query: any, user: JwtAccessPayload) => {
  const { page, limit, cameraId, status, priority, type } = query;
  const filter: any = {};

  if (cameraId) {
    const camera = await Camera.findOne({ _id: cameraId, isDeleted: false });
    if (!camera) throw ApiError.notFound("Camera");
    await validateCameraAccess(camera, user);
    filter.cameraId = cameraId;
  } else if (user.role !== "super_admin" && user.role !== "admin") {
    // If no cameraId provided, non-admins can only see alerts for their assigned cameras
    const accessibleCameras = await Camera.find({
      $or: [{ operatorIds: user.userId }, { customerId: user.userId }],
      isDeleted: false,
    }).select("_id");
    filter.cameraId = { $in: accessibleCameras.map((c) => c._id) };
  }

  if (status) filter.status = status;
  if (priority) filter.priority = priority;
  if (type) filter.type = type;

  const skip = (page - 1) * limit;
  const [alerts, total] = await Promise.all([
    Alert.find(filter)
      .populate("cameraId", "name serialNumber")
      .populate("createdBy", "name role")
      .populate("assignedTo", "name role")
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limit)
      .lean(),
    Alert.countDocuments(filter),
  ]);

  return { alerts, total, page, limit, totalPages: Math.ceil(total / limit) };
};

/**
 * Get Alert Details
 * Fetches the full details of a specific alert, including populated camera and user references.
 * Ensures the requesting user has access to the camera associated with the alert.
 * 
 * @param id - The alert ID
 * @param user - The requesting user
 */
export const getAlertDetails = async (id: string, user: JwtAccessPayload) => {
  const alert = await Alert.findById(id)
    .populate("cameraId", "name serialNumber operatorIds customerId")
    .populate("createdBy", "name role")
    .populate("assignedTo", "name role")
    .lean();
    
  if (!alert) throw ApiError.notFound("Alert");

  const camera = await Camera.findById(alert.cameraId).lean();
  if (camera) {
    await validateCameraAccess(camera as any, user);
  }

  return alert;
};

/**
 * Acknowledge Alert
 * Claims an alert by setting its status to 'acknowledged' and assigning it to the operator.
 * Emits an 'alert_acknowledged' socket event to notify other dashboards.
 * 
 * @param id - The alert ID
 * @param user - The operator claiming the alert
 */
export const acknowledgeAlert = async (id: string, user: JwtAccessPayload) => {
  const alert = await Alert.findById(id);
  if (!alert) throw ApiError.notFound("Alert");

  const camera = await Camera.findOne({ _id: alert.cameraId, isDeleted: false });
  if (!camera) throw ApiError.notFound("Camera");
  await validateCameraAccess(camera, user);

  if (alert.status !== "new") {
    throw ApiError.badRequest("Alert is not in 'new' state");
  }

  alert.status = "acknowledged";
  alert.assignedTo = new mongoose.Types.ObjectId(user.userId);
  alert.acknowledgedAt = new Date();
  await alert.save();

  socketService.emitToCamera(alert.cameraId.toString(), "alert_acknowledged", alert);

  logActivity({
    userId: new mongoose.Types.ObjectId(user.userId),
    action: "ALERT_ACKNOWLEDGED",
    description: `Acknowledged alert ${alert._id}`,
    metadata: { alertId: alert._id },
  });

  return alert;
};

/**
 * Resolve Alert
 * Closes an alert, adding resolution notes. 
 * Emits an 'alert_resolved' socket event to clear it from active dashboards.
 * 
 * @param id - The alert ID
 * @param resolutionNotes - Notes explaining how the alert was resolved
 * @param user - The operator resolving the alert
 */
export const resolveAlert = async (id: string, resolutionNotes: string, user: JwtAccessPayload) => {
  const alert = await Alert.findById(id);
  if (!alert) throw ApiError.notFound("Alert");

  const camera = await Camera.findOne({ _id: alert.cameraId, isDeleted: false });
  if (!camera) throw ApiError.notFound("Camera");
  await validateCameraAccess(camera, user);

  if (alert.status === "resolved") {
    throw ApiError.badRequest("Alert is already resolved");
  }

  alert.status = "resolved";
  alert.resolvedAt = new Date();
  alert.resolutionNotes = resolutionNotes;
  
  if (!alert.assignedTo) {
      alert.assignedTo = new mongoose.Types.ObjectId(user.userId);
  }

  await alert.save();

  socketService.emitToCamera(alert.cameraId.toString(), "alert_resolved", alert);

  // TODO: Implement Incident Creation here if the alert requires an incident report (Module 11)

  logActivity({
    userId: new mongoose.Types.ObjectId(user.userId),
    action: "ALERT_RESOLVED",
    description: `Resolved alert ${alert._id}`,
    metadata: { alertId: alert._id },
  });

  return alert;
};

/**
 * Escalate Alert
 * Elevates the status of an alert to 'escalated'.
 * Emits an 'alert_escalated' socket event.
 * 
 * @param id - The alert ID
 * @param user - The operator escalating the alert
 */
export const escalateAlert = async (id: string, user: JwtAccessPayload) => {
  const alert = await Alert.findById(id);
  if (!alert) throw ApiError.notFound("Alert");

  const camera = await Camera.findOne({ _id: alert.cameraId, isDeleted: false });
  if (!camera) throw ApiError.notFound("Camera");
  await validateCameraAccess(camera, user);

  alert.status = "escalated";
  await alert.save();

  socketService.emitToCamera(alert.cameraId.toString(), "alert_escalated", alert);

  logActivity({
    userId: new mongoose.Types.ObjectId(user.userId),
    action: "ALERT_ESCALATED",
    description: `Escalated alert ${alert._id}`,
    metadata: { alertId: alert._id },
  });

  return alert;
};

/**
 * Get Pending Alerts
 * Fetches all 'new' and 'acknowledged' alerts for the dashboard.
 * Filtered by the cameras the requesting operator is assigned to.
 * 
 * @param user - The requesting operator
 */
export const getPendingAlerts = async (user: JwtAccessPayload) => {
  // Get all 'new' and 'acknowledged' alerts for cameras accessible by this user
  let filter: any = { status: { $in: ["new", "acknowledged"] } };

  if (user.role !== "super_admin" && user.role !== "admin") {
    const accessibleCameras = await Camera.find({
      $or: [{ operatorIds: user.userId }, { customerId: user.userId }],
      isDeleted: false,
    }).select("_id");
    filter.cameraId = { $in: accessibleCameras.map((c) => c._id) };
  }

  const alerts = await Alert.find(filter)
    .populate("cameraId", "name")
    .sort({ createdAt: -1 })
    .lean();

  return alerts;
};

/**
 * Get Global Alert Stats (Admin Only)
 * Aggregates all alerts across the system to provide a status breakdown.
 * 
 * @param user - The requesting admin user
 */
export const getAlertStats = async (user: JwtAccessPayload) => {
  // Only admins get global stats
  if (user.role !== "super_admin" && user.role !== "admin") {
    throw ApiError.forbidden("Requires admin privileges");
  }

  const stats = await Alert.aggregate([
    { $group: { _id: "$status", count: { $sum: 1 } } },
  ]);

  const formattedStats = {
    new: 0,
    acknowledged: 0,
    resolved: 0,
    escalated: 0,
    total: 0,
  };

  stats.forEach((stat) => {
    formattedStats[stat._id as keyof typeof formattedStats] = stat.count;
    formattedStats.total += stat.count;
  });

  return formattedStats;
};
